import React from "react";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google"; // Import Montserrat

import { AuthProvider } from "@/context/AuthContext";
import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"], weight: ["400", "700"] }); // Use Montserrat with specific weights

export const metadata: Metadata = {
  title: "frontend-developer-assignment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        {/* Apply Montserrat - Sinelec font */}
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
